### ISSUE TITLE
[Doc] Missing doc on compilation pipeline

### ISSUE THREAD

**Issue by sbancal** [EPFL-ENAC/CCFatiguePlatform#109]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On branch _develop_, I run `make api` ... and get :

> make -C backend api
> make[1]: Entering directory '/home/sbancal/IT4R/CCFatiguePlatform/backend'
> POSTGRES_PASSWORD="" poetry run python api.py ../openapi.json
> Traceback (most recent call last):
>   File "/home/sbancal/IT4R/CCFatiguePlatform/backend/api.py", line 8, in <module>
>     from ccfatigue.main import app
>   File "/home/sbancal/IT4R/CCFatiguePlatform/backend/ccfatigue/main.py", line 8, in <module>
>     from ccfatigue.routers import root, experiments, tests, analysis
>   File "/home/sbancal/IT4R/CCFatiguePlatform/backend/ccfatigue/routers/analysis.py", line 7, in <module>
>     from ccfatigue.analyzer import run_sn_curve
>   File "/home/sbancal/IT4R/CCFatiguePlatform/backend/ccfatigue/analyzer.py", line 15, in <module>
>     import ccfatigue.modules.sn_curve_sendeckyj as sn_curve_sendeckyj
>   File "/home/sbancal/IT4R/CCFatiguePlatform/backend/ccfatigue/modules/sn_curve_sendeckyj.py", line 30, in <module>
>     import ccfatigue.fortran.sendeckyj as sendeckyj  # Fortran optimized functions
> ModuleNotFoundError: No module named 'ccfatigue.fortran'
> make[1]: *** [Makefile:20: api] Error 1
> make[1]: Leaving directory '/home/sbancal/IT4R/CCFatiguePlatform/backend'
> make: *** [Makefile:26: api] Error 2

Apparently I was missing the `make compile` inside `backend` folder.

### Expected Behavior

- _README.md_ file documents how to setup the env so that we can run anything.
- the step to setup should be launchable from the root of the project

### Steps To Reproduce

```bash
make api
```

### Environment

```markdown
- OS: U22.04
```

### Anything else?

thks : )

**Comment by nicdub** [comment]
Fixed by @sbancal in issue #152 (added `make compile` to root `make install`)
