### ISSUE TITLE
CYC Data convention

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/CCFatiguePlatform#111]
Do you have documentation for that module - as well as other examples of inputs and outputs to help us ? 
 
Load spectrum input ([example input](https://github.com/EPFL-ENAC/CCFatiguePlatform/tree/develop/CCFatigue_modules/1_CycleCounting)) is the peak ? 
 
Outputs ([example output](https://github.com/EPFL-ENAC/CCFatiguePlatform/blob/develop/CCFatigue_modules/1_CycleCounting/output.txt)) should be, according to our last discussion, the 5 columns described [here in the CYC Data convention](https://github.com/EPFL-ENAC/CCFatiguePlatform/blob/develop/Data/CYC_Data_Convention.md). However, 
- column 3 doesn’t look like R ratios at all !! What is it?
- Columns 4 should be “number_of_cycles” or “number_of_cycles_to_failure” ? 
- Column 5 is “cumulative_number_of_cycles" you said, but as a percentage, right?
 
Detailed documentation on module 1’s methods would really help !

**Comment by vassilop** [comment]
This is closed
