### ISSUE TITLE
[New Feature] : QS Dashboard implementation

### ISSUE THREAD

**Issue by sbancal** [EPFL-ENAC/CCFatiguePlatform#120]
### Not a duplicate

- [X] I have checked that this feature is not already present in the [open issues](https://github.com/EPFL-ENAC/CCFatiguePlatform/issues/)

### Feature description

As it is for FA, we need a dedicated QS Dashboard.

# 1st graph to prepare: QS with fracture
- title "Crack Load vs Crack Displacement".
- legend: "Specimen name"
- x-axis: `Crack_Displacement`
- y-axis-left: `Crack_Load` with line
- y-axis-right: `Crack_length` with `'o'`
- dataset to test: `Data/preprocessed/TST_Wang_2020-12_QS`

# 2nd graph: QS with/without fracture
- title "Load vs Displacement"
- legend: "Specimen name"
- x-axis: from a dropdown (where `#` is an id). Suggest only the one that are present in the CSV. Possibles values:
  - Machine_Displacement
  - MD_Displacement--#
  - u--#
  - v--#
- y-axis: either `Machine_Load` or `MD_Load--#` depending the one present in the CSV. id `MD_Load--#` then use same id as x-axis.
- dataset to test: `Data/preprocessed/TST_Wang_2020-12_QS`

# 3rd graph: QS without fracture

- title: "Stress vs Strain"
- legend: "Specimen name"
- x-axis: labeled "Strain": from dropdown one of:
  - exx--#
  - eyy--#
  - exy--#
- y-axis: labeled "Stress" processed as : `load / (width * thickness)` where `load` is one of `MD_Load--#` or `Machine_Load` (give a dropdown if several available).
`width` and `thickness` are taken from `Data/preprocessed/experimentXYZ/tests.csv`
- dataset to test: `Data/preprocessed/TST_Wang_2021-11_QS`

Specifications written on paper `2022-09-29`, as discussed between @vsdharun and @sbancal .

![20220929_151108](https://user-images.githubusercontent.com/895546/193040974-3ac212ba-ac27-45e6-ae02-c74a5582b5e4.jpg)
![20220929_151115](https://user-images.githubusercontent.com/895546/193041000-cad97c64-3fa4-4ffe-8a3e-351c387ea75d.jpg)
![20220929_151131](https://user-images.githubusercontent.com/895546/193041038-90fca39c-f403-4de8-bc30-41d6799f3cc5.jpg)

**Comment by blueur** [comment]
@sbancal missing exx--#, eyy--# or exy--# for TST_Wang_2021-11_QS but found it in TST_Liu_2021-12_QS

**Comment by blueur** [comment]
@sbancal in TST_Liu_2021-12_QS, missing width and thickness..

**Comment by sbancal** [comment]
@vsdharun 
We're unable to prepare the "Stress vs Strain" plot as we don't find dataset that provide the necessary fields.
Do you have such dataset ?

**Comment by vsdharun** [comment]
@sbancal  I remember uploading the test data "TST_Srinivasan_2021-10_QS". Could you preprocess it? 
Then, I will add the specimen thickness and width in that metadata file.

**Comment by sbancal** [comment]
@vsdharun Thanks for your answer.
Dataset "TST_Srinivasan_2021-10_QS" is not yet injected because it has inconsistencies I explained here #97 .
Could you answer the question there ... so that I can inject it and that we can use it ?

In the mean time, [Dataset checker](https://ccfatigue-test.epfl.ch/fatigue_database/data_upload) has been implemented, so you can use it to validate your modifications.

Thank you

**Comment by vsdharun** [comment]
@sbancal I tried the data checker, but it takes more time to validate my result. I copied the zip file for validation. If this passes, you can plot the stress-strain diagrams.
[TST_Srinivasan_2021-10_QS.zip](https://github.com/EPFL-ENAC/CCFatiguePlatform/files/9786831/TST_Srinivasan_2021-10_QS.zip)

**Comment by sbancal** [comment]
Woops, preprocessing crashes with your dataset. I reported it on #139 
I'll fix it and let you know.

**Comment by sbancal** [comment]
@vsdharun 
`TST_2021-10_QS_metadata.xlsx` doesn't follow https://github.com/EPFL-ENAC/CCFatiguePlatform/blob/develop/Data/TST_Data_Template.xls .
Line 3 named _Definition_ must be deleted in order to be processed.

When removed, the preprocessing validation pipeline will work and indicate you of what has to be fixed.
Let me know!

**Comment by sbancal** [comment]
@blueur as discussed, I rebased 2 first commit of branch origin/feature/quasi-static to deploy it this morning.

It gives correct output on _TST_Wang_2020-12_QS_ experiment, but gives **500** errors on other _QS_ experiments.
Thanks to fix it 😉

**Comment by blueur** [comment]
@sbancal @vsdharun 
For QS without fracture, only columns `exx--1`, `eyy--1` and `exy--1` are currently processed due to missing test case. We would need at least a second number to implement `exx-#`.

**Comment by johnzer123** [comment]
I checked my data, TST_Wang_2021-11_QS, which should have passed the reqiurement. There we have u--1, v--1 and u--2, v--2. Not exx-#, but they should be similar. 

[TST_Wang_2021-11_QS](https://github.com/EPFL-ENAC/CCFatiguePlatform/tree/develop/Data/preprocessed/TST_Wang_2021-11_QS)

**Comment by blueur** [comment]
@LuluLiu-CCLab
For the "Load vs Displacement" graph, we take all possible values (Machine_Displacement, u--#, MD_Load--#, ...) and filter out all lines which contain null values. 
Since MD_Load--1 contains only null values, all lines are skip in `TST_Liu_2021-12_QS`. 
Can you either remove null columns or fill them ?

**Comment by LuluLiu-CCLab** [comment]
Hi, Blueur. I am sorry I did not get your point after checking my data. Could you explain more to me, please?

**Comment by blueur** [comment]
@LuluLiu-CCLab If I take the first test measure in `TST_Liu_2021-12_QS`, the column `MD_Load--1` contains no value. 
So I was wondering if values are missing or can you remove this columns ?
There are more empty columns, for instance `Machine_Time`, ...

**Comment by LuluLiu-CCLab** [comment]
> Hi, Blueur. I am sorry I did not get your point after checking my data. Could you explain more to me, please?


@blueur Ok. No problem. Many thanks. Do you think it is fine if I remove all empty columns and only keep those with the values?
>

**Comment by blueur** [comment]
@LuluLiu-CCLab Yep, it would be fine, thanks in advance ! ^^

**Comment by sbancal** [comment]
FIX by #172
