### ISSUE TITLE
(Fortran2Py) > Mod 3 + 5 Harris EXE files

### ISSUE THREAD

**Issue by nicdub** [EPFL-ENAC/CCFatiguePlatform#121]
Hi Tassos,

Could you attach here the fortran Windows exe files for mod 3 CLD Harris and mod 5 Miner Harris? They both include libraries we don't have.
Could you also add input files to test them?

Thanks
Nicolas

**Comment by vassilop** [comment]
[Harris_CLD_and_Miner.zip](https://github.com/EPFL-ENAC/CCFatiguePlatform/files/9754462/Harris_CLD_and_Miner.zip)

**Comment by vassilop** [comment]
Hello Nicolas, here is what I have related to Harris CLD and Miner_Harris

**Comment by nicdub** [comment]
Hi Tassos, thank you for the files, it helped to correct a bug I didn't see.
