### ISSUE TITLE
[BUG] FA, right box fields change

### ISSUE THREAD

**Issue by sbancal** [EPFL-ENAC/CCFatiguePlatform#130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Current box fields are:

- Specimen number:   1
- Stress at failure:   -
- Strain at failure:   - 
- N_cycles:   0
- R:   -
- Total dissipated energy (TDE):   731 

### Expected Behavior

We expect the following fields:

- Specimen number:   1
- Stress at failure:   -
- Strain at failure:   - 
- cycle at failure:  blabla (only if failure)
- run out: True or False
- R:   -
- Total dissipated energy (TDE):   731 

### Steps To Reproduce

go to https://ccfatigue-test.epfl.ch/fatigue_database/tests_dashboard?exp=2&tests=5

### Environment

```markdown
any
```

**Comment by sbancal** [comment]
@ShayanKhl I'm working on this and have some questions. I put them here (maybe there will be more messages here)

1. we said `cycle at failure: number (only if failure)`.
Does `only if failure` means `only if fracture` ?

2. What is the column I will use to get that `cycle at failure`?
  - `Machine_N_cycles` ?
  - `MD_N_cycles--1` ?
  - something else ?

3. I guess, I read the latest value from the column specified in question _2._ Correct ?

4. I have no dataset matching _FA_ and _fracture = true_
How shall I test it ?


Thnks

**Comment by sbancal** [comment]
@ShayanKhl 
For every field in the right box, there is a tooltip that describes the meaning.
e.g. N_cycles: defined as the number of cycles to failure [-]

What tooltip shall I put for run out ?

**Comment by sbancal** [comment]
@ShayanKhl as discussed with @vsdharun 

- `cycle at failure` is the same as `N_fail`. It's not depending on fracture or not.
- we expect all available (1 or 2) from Machine_n_cycles and MD_n_cycles

**Comment by sbancal** [comment]
@ShayanKhl @vsdharun 
Looking at the still missing fields:

- `Stress at failure`
  I'll put the stress value at the last cycle (N_fail cycle)
- `Strain at failure`
  I'll put the strain value at the last cycle (N_fail cycle)
- `R`
  Could you tell me how I must calculate this please ?

Thanks

**Comment by vsdharun** [comment]
@sbancal 

> * `Stress at failure`
>  Highest one from N_fail cycle 
> * `Strain at failure`
>   Highest one from N_fail cycle
> * `R`
>   It is given in the testing sheet of metadata file.
>

**Comment by sbancal** [comment]
thank you @vsdharun , that will be implemented as soon as I'm back on that project, next week.

**Comment by sbancal** [comment]
Note:

`R` is `stress ratio`
