### ISSUE TITLE
N_fail has to be processed

### ISSUE THREAD

**Issue by sbancal** [EPFL-ENAC/CCFatiguePlatform#136]
https://github.com/EPFL-ENAC/CCFatiguePlatform/blob/a5332e88aff840b444379acd2470031585fe0a87/backend/preprocessing/hysteresis_loops.py#L149

Please calculate this from the dataset.

**Comment by ShayanKhl** [comment]
@sbancal Normally, it should be the last cycle recorded of the fatigue test...

**Comment by sbancal** [comment]
@ShayanKhl , we discussed this with @vsdharun 

- he confirms it's only related to _Fatigue_
- we have 1 _N_fail_ per test. So current formula puts it to the experiment is completely wrong.
- it's for all, Fracture and no fracture
- it's confirmed for the values taken from TST_Khalooei_2021-10_FA dataset.
  If we use Machine_* then take it from the maximum `Machine_n_cycle`
  if we use MD_* then take it from the maximum `MD_n_cycle`
