### ISSUE TITLE
[BUG] QS Data without fracture

### ISSUE THREAD

**Issue by blueur** [EPFL-ENAC/CCFatiguePlatform#147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

No experiment matches the requirement defined in https://github.com/EPFL-ENAC/CCFatiguePlatform/issues/120 for QS without fracture. 
In `TST_Srinivasan_2021-10_QS`, the second graph cannot be computed because the displacement column is missing. 

### Expected Behavior

A complete experiment data without fracture following specification in https://github.com/EPFL-ENAC/CCFatiguePlatform/issues/120

**Comment by vsdharun** [comment]
Hello, If the displacement is not provided, we need not to plot the second graph.

**Comment by blueur** [comment]
Ok thanks ! 
I meant the 3rd graph described in https://github.com/EPFL-ENAC/CCFatiguePlatform/issues/120 which is the stress-strain. ;)
