### ISSUE TITLE
[REFACTOR] Define naming conventions for the CCFatigue analysis

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/CCFatiguePlatform#151]

**Comment by nicdub** [comment]
Explicit names?
1. `cycle_counting_...`
2. `s-n_curve_...`
3. `constant_life_diagram_...`
4. `fatigue_failure_...`
5. `damage_summation_...`

**Comment by charlottegiseleweil** [comment]
@nicdub I like your suggestion, should we mabe just cut "-" and "_" in the module name to separate more explicitly module and method ? so naming convention would be {modulename}_{methodname} (without spaces, "_"..) ? Edited with my suggestion above.

**Comment by nicdub** [comment]
@charlottegiseleweil sorry to go back but I tried explicit names, it's vers long:
`constantlifediagram_piecewiselinear.py`
`import ccfatigue.modules.constantlifediagram_piecewiselinear as constantlifediagram_piecewiselinear`

Maybe we should use short version?
`cld_piecewiselinear.py`
`import ccfatigue.modules.cld_piecewiselinear as cld_piecewiselinear`
