### ISSUE TITLE
FA & QS graphs units

### ISSUE THREAD

**Issue by sbancal** [EPFL-ENAC/CCFatiguePlatform#157]
Add units on FA & QS graphs

**Comment by sbancal** [comment]
@ShayanKhl could you confirm that unit for the Hysteresis area is `[mm*kN/N]`

**Comment by sbancal** [comment]
@vsdharun could you confirm the following units ?

- Crack Displacement: `[mm]`
- Crack Load: `[kN/N]`
- Crack Length: `[mm]`
- Machine Displacement: `[mm]`
- Machine Load: `[kN/N]`
- Strain: `[-]`
- Stress: `[kN/N]`

**Comment by vsdharun** [comment]
@sbancal  Please check the below response.
> * Crack Displacement: `[mm]`
> * Crack Load: `[kN or N]`
> * Crack Length: `[mm]`
> * Machine Displacement: `[mm]`
> * Machine Load: `[kN or N]`
> * Strain: `[-]`
> * Stress: `[N/mm2 or MPa]`

**Comment by vsdharun** [comment]
Thanks for flagging it. Both are the same unit.  
> * `[-]` for _FA_
> * `[-]` for _QS_
>

**Comment by sbancal** [comment]
> Thanks for flagging it. Both are the same unit.
> 
> > * `[-]` for _FA_
> > * `[-]` for _QS_

Ok. Then I have an other question. `strain` for _FA_ graph [comes from](https://github.com/EPFL-ENAC/CCFatiguePlatform/blob/89bfa44d83abad02476b95575bd99bfd76a54380/backend/ccfatigue/experiment/fatigue.py#L89) `Machine_Displacement` column which is [documented](https://github.com/EPFL-ENAC/CCFatiguePlatform/blob/89bfa44d83abad02476b95575bd99bfd76a54380/Data/TST_Data_Convention.md?plain=1#L42) to be of unit `[mm]`.

What do we do with this ?
- keep the convention and the algorithm as is, and set the unit to be `[-]` ?
- fix something in the convention ?
- fix something in the algorithm ?

**Comment by sbancal** [comment]
After fixing _stress_ unit to `[MPa]` for _QS_, I doubled checked stress for _FA_.
It [comes from](https://github.com/EPFL-ENAC/CCFatiguePlatform/blob/89bfa44d83abad02476b95575bd99bfd76a54380/backend/ccfatigue/experiment/fatigue.py#L90) `Machine_Load` column [documented](https://github.com/EPFL-ENAC/CCFatiguePlatform/blob/89bfa44d83abad02476b95575bd99bfd76a54380/Data/TST_Data_Convention.md?plain=1#L43) to be of unit `[kN]/[N]`.

Is it ok that both _stress_ don't have the same unit ?

**Comment by sbancal** [comment]
> > Thanks for flagging it. Both are the same unit.
> > > * `[-]` for _FA_
> > > * `[-]` for _QS_
> 
> Ok. Then I have an other question. `strain` for _FA_ graph [comes from](https://github.com/EPFL-ENAC/CCFatiguePlatform/blob/89bfa44d83abad02476b95575bd99bfd76a54380/backend/ccfatigue/experiment/fatigue.py#L89) `Machine_Displacement` column which is [documented](https://github.com/EPFL-ENAC/CCFatiguePlatform/blob/89bfa44d83abad02476b95575bd99bfd76a54380/Data/TST_Data_Convention.md?plain=1#L42) to be of unit `[mm]`.
> 
> What do we do with this ?
> 
>     * keep the convention and the algorithm as is, and set the unit to be `[-]` ?
> 
>     * fix something in the convention ?
> 
>     * fix something in the algorithm ?

will be fixed by #162

**Comment by sbancal** [comment]
@ShayanKhl Could you confirm the following units for _FA_ please:

- `Strain`: [-]
- `Stress`: [MPa]
- `Number of cycles`: [-]
- `Hysteresis area`: [mm*N]
- `Creep`: [mm]
- `Stiffness`: [-]

Thks

**Comment by sbancal** [comment]
@ShayanKhl we doubled checked with @vsdharun and found the following units:

- `Strain`: [-]
- `Stress`: [MPa]
- `Number of cycles`: [-]
- `Hysteresis area`: [N/mm²]
- `Creep`: [-]
- `Stiffness`: [N/mm²]
