### ISSUE TITLE
FIX Stress vs Strain calculations

### ISSUE THREAD

**Issue by sbancal** [EPFL-ENAC/CCFatiguePlatform#162]
Currently, Stress vs Strain for _FA_ is calculated fatigue.py line 89

And we expect it to be fixed like this:

Shayan + Dharun ask:

if we have Machine n cycles, then
strain = machine displacement / specimen length
stress = Machine_Load[i] / (specimen width * thickness)

otherwise if I have MD n cycles, then
strain1 = exx-1
strain2 = md displacement / specimen length
stress = MD_Load[i] / (specimen width * thickness)

**Comment by sbancal** [comment]
@sbancal notify @vsdharun @ShayanKhl as soon as it's implemented on the server.

**Comment by sbancal** [comment]
We are missing data ... again.

the formula given requires the specimen `length`. But this is present in only 1 of the 3 _FA_ dataset.
The following datasets are missing the specimen `length` field. Please provide it. I need to implement your request.

-  _TST_Khalooei_2021-10_FA_ @ShayanKhl 
- _TST_Srinivasan_2021-10_FA_ @vsdharun 

For this reason, I'll add the constraint of `length` column for every _FA_ dataset to the data convention and data validation pipeline.

Regards

**Comment by sbancal** [comment]
@ShayanKhl @vsdharun 

Stress and Strain are calculated, no matter if _fracture_ or not. Correct ?

I ask this, because I see the constraint on `width` and `thickness` is only for _FA_ with no _fracture_

**Comment by vsdharun** [comment]
> 

@sbancal Please note that the specimen length of the TST_Srinivasan_2021-10_FA is 65 mm.

**Comment by vsdharun** [comment]
> @ShayanKhl @vsdharun
> 
> Stress and Strain are calculated, no matter if _fracture_ or not. Correct ?
> 
> I ask this, because I see the constraint on `width` and `thickness` is only for _FA_ with no _fracture_

Stress and strain are calculated only for FA with no fracture

**Comment by sbancal** [comment]
> Stress and strain are calculated only for FA with no fracture

Oh ... I'm surprised ! That means if we have _FA_ dataset with fracture, we shouldn't show the stress-strain graph !?
What about the other graphs ?
Hysteresis graph, Creep and Stiffness are calculated from stress and strain values ... that means it must not be shown either?

**Comment by vsdharun** [comment]
> > Stress and strain are calculated only for FA with no fracture
> 
> Oh ... I'm surprised ! That means if we have _FA_ dataset with fracture, we shouldn't show the stress-strain graph !? What about the other graphs ? Hysteresis graph, Creep and Stiffness are calculated from stress and strain values ... that means it must not be shown either?

Incase of fatigue with fracture, we have only cracklength vs cycles graph. We will not have any other graph.. @vassilop please correct me, If I am wrong.

**Comment by sbancal** [comment]
Dear @vsdharun , I've pushed fixed algorithm on https://ccfatigue-test.epfl.ch/ .
Could you confirm, please, that stress and strain are correct for you now ?
thank you

**Comment by ShayanKhl** [comment]
@sbancal Thanks, please also consider that my specimens' length is 160 mm...

**Comment by sbancal** [comment]
> @sbancal Thanks, please also consider that my specimens' length is 160 mm...

ok. This is followed in #209

**Comment by vsdharun** [comment]
In principle, the plots seem correct. @sbancal The load values should have been in _N_. Currently, the uploaded data is in _KN_. Is it possible to multiply the _machine and MD loads column by 1000 ?_. I think this should be done for @ShayanKhl data as well!

Please let me know your thoughts. 

We can do the final confirmation after this.

**Comment by sbancal** [comment]
Thank you @vsdharun for your answer.
I fixed this on https://ccfatigue-test.epfl.ch
Can you confirm it matches your expectations ? (It has an impact also on _Hysteresis loop area evolution_ and _Stiffness evolution under cyclic loading_ graphs)
