### ISSUE TITLE
[Dataset] TST_Khalooei_2021-10_FA doesn't match new requirements

### ISSUE THREAD

**Issue by sbancal** [EPFL-ENAC/CCFatiguePlatform#169]
Dear @ShayanKhl 
As we discussed together with @vsdharun , _FA_ experiments with no fracture have now 2 new constraints:

- `width`
- `thickness`

This is described in #163 and needed by #162.

Your Dataset `TST_Khalooei_2021-10_FA` is missing these 2 columns.
Could you provide it please so that I can integrate your data again ?

Thanks

**Comment by ShayanKhl** [comment]
Dear @sbancal,

Thanks, there are as below:
width = 25.0 mm 
thickness = 2.8 mm

**Comment by sbancal** [comment]
Thanks @ShayanKhl for your quick answer.
Could you confirm that the `width` and `thickness` are the same for all 23 specimens?
thks

**Comment by ShayanKhl** [comment]
@sbancal Yes, same for all...
