### ISSUE TITLE
(TST Preprocessing)

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/CCFatiguePlatform#29]
Preprocessing pipeline

- [x] tst_data_quality_control.py 
- [x] delete TST_data_harmonization.py if obsolete
- [x] Validate/convert new TST datasets (pull requests)
  - [x] TST_Khalooei_2021-10_FA
  - [x] TST_Srinivasan_2021-10_FA
  - [x] https://github.com/EPFL-ENAC/CCFatiguePlatform/pull/45
  - [x] https://github.com/EPFL-ENAC/CCFatiguePlatform/pull/46
  - [x] https://github.com/EPFL-ENAC/CCFatiguePlatform/pull/47
  - [x] https://github.com/EPFL-ENAC/CCFatiguePlatform/pull/48
  - [x] https://github.com/EPFL-ENAC/CCFatiguePlatform/pull/49
  - [x] https://github.com/EPFL-ENAC/CCFatiguePlatform/pull/50 ➡️ impossible as is
  - [x] https://github.com/EPFL-ENAC/CCFatiguePlatform/pull/51 ➡️ impossible as is
- [x] implement constraint checks on xls/json files
- [x] Code review

**Comment by sbancal** [comment]
Preprocessing is approved now. 👍🏼
