### ISSUE TITLE
(DB : Test Dashboard)

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/CCFatiguePlatform#35]
- [ ] Migration eCharts ?

**Comment by pierreleripoll** [comment]
Hi ! I took a look today, how do would you like to proceed ? 

Should I modify backend api to fetch data to populate the plots ? It requires creating new tables in database and populate them with CSV files include inside fakedata directory. I don't quiet understand why this directory exists, should data not be inside Data directory ? What's the difference beetween these two ?

I tried to use the existing bokeh_plots functions, but I don't think the result will be as nice and readable if I use them. I guess in the end we won't be reading csv files but fetching the database anyway ? So maybe it's better to do it this way as soon as possible ?

If someone is available those days we could discuss the best way to migrate to echarts !

**Comment by sbancal** [comment]
echarts is done 👍🏼
