### ISSUE TITLE
DB: Data checker (in "Data Upload" tab)

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/CCFatiguePlatform#52]
Data Upload tab : 

- [x] Users load zip of folder TST_... contining data and metadata
- [x] Preprocessing scripts run and returns error log or a message "Your data is valid!" (then  "Load yr data on Github" (link to New issue)"

Leave for later : 
- [ ] Integration à la DB

**Comment by sbancal** [comment]
done
