### ISSUE TITLE
(DB) Error in column name for TST_Khalooei_2021-10_FA

### ISSUE THREAD

**Issue by sbancal** [EPFL-ENAC/CCFatiguePlatform#53]
All 23 csv files from dataset `TST_Khalooei_2021-10_FA`  have a column named  `Camera_N_cycles` which is not matching current TST_DATA_Convention as discussed here https://github.com/EPFL-ENAC/CCFatiguePlatform/pull/38 .

Should it be renamed to `MD_N_cycles--1` or `Crack_N_cycles` ? Or even something else ?

https://github.com/EPFL-ENAC/CCFatiguePlatform/blob/09853c0d6b0f431049eff5aa803b912c77cb23d6/Data/TST_Khalooei_2021-10_FA/TST_2021-10_FA_15.csv#L1

**Comment by ShayanKhl** [comment]
> All 23 csv files from dataset `TST_Khalooei_2021-10_FA` have a column named `Camera_N_cycles` which is not matching current TST_DATA_Convention as discussed here #38 .
> 
> Should it be renamed to `MD_N_cycles--1` or `Crack_N_cycles` ? Or even something else ?
> 
> https://github.com/EPFL-ENAC/CCFatiguePlatform/blob/09853c0d6b0f431049eff5aa803b912c77cb23d6/Data/TST_Khalooei_2021-10_FA/TST_2021-10_FA_15.csv#L1

Yes, I had prepared my tests before the finalized conventions. According to the updated conventions, Camera_N_Cycles should be replaced by MD_N_Cycles. The column "index" is not also compatible and it should be MD_Index...
