### ISSUE TITLE
TST_Data_Convention review

### ISSUE THREAD

**Issue by sbancal** [EPFL-ENAC/CCFatiguePlatform#55]
Hello,

I didn't notice the data type. But the `Machine_Time` and `Th_time` should be either **Double** or in hh:mm:ss.00 (ss in Double precision). Also we missed a column `MD_time`, whose type also be **Double** or hh:mm:ss.00. 
Could you update these changes? 
Seems there were some mistakes from our side. I am sorry for that. But these changes have been agreed among us for a long time. I don't know why we didn't include these in the last convention file...

_Originally posted by @johnzer123 in https://github.com/EPFL-ENAC/CCFatiguePlatform/issues/50#issuecomment-1190124036_

**Comment by sbancal** [comment]
Waiting to know if they expect `MD_time` or `MD_time--#`.
Discussion in #50

**Comment by vsdharun** [comment]
It is "MD_time"

**Comment by sbancal** [comment]
They expepct `MD_time--#`

**Comment by johnzer123** [comment]
> They expepct `MD_time--#`

`MD_time--#` indeed. Sorry for the confusion.

**Comment by sbancal** [comment]
**Please comment here for any update about the Data Convention**

**Comment by vsdharun** [comment]
[TST_Data_Template.xls](https://github.com/EPFL-ENAC/CCFatiguePlatform/files/9350393/TST_Data_Template.xls)

Please note that this is a metadata template.

**Comment by sbancal** [comment]
Thank you @vsdharun 

One question : I see that `Sample type` new column in Experiment tab is under no main section. As it is between `Publication` and `Material Type`, my guess is that it should be under `Material Type`. Could you confirm please ?

thank you

**Comment by sbancal** [comment]
Also in Tests tab, I see that `Specimen name` has no description (at least : type, unit).
Could you confirm it is a String, with no type ?

**Comment by vsdharun** [comment]
> 

Yeah, it comes under material type..Thanks

**Comment by sbancal** [comment]
and not mandatory ?

**Comment by vsdharun** [comment]
> and not mandatory
It is optional..

**Comment by sbancal** [comment]
Other question : 
In the Tests tab, I see `x corrdinate of measuring point #` and `y corrdinate of measuring point #`. Does that mean it will have as many columns as the measuring points ?
`#` having the same meaning than `--#` in the csv files ?

**Comment by vsdharun** [comment]
Yes, it is a similar meaning in the csv files. # means 'n' number of points can be added.

**Comment by sbancal** [comment]
Oh ... ok.
This means a quite big change in our database schema. I'll investigate.

**Comment by sbancal** [comment]
While implementing the specification changes, I'd like to validate with you that this is what you want (this summarize a part of the differences I see between previous and actual `TST_Data_Template.xls` file) : 

# Experiment tab

## removed columns :

- General>Initial Crack length
- Material Type>Fiber Geometry
- Geometry>Length
- Geometry>Width
- Geometry>Thickness
- Laminates and Assemblies>Fiber Content
- Test condtions>Temperature
- Test condtions>Humidity

## added columns :

- General>Quasi-static test type
- General>Temperature test type
- Material Type>Sample type
- Material Type>Fiber form
- Laminates and Assemblies>Fiber volume ratio
- Measurement>Measuring points

# Tests tab :

## removed columns :

- Loading rate

## added columns :

- Specimen name
- Frequency
- Displacement controlled loading rate
- Load controlled loading rate
- Length
- Width
- Thickness
- Temperature
- Humidity
- initial crack length
- x corrdinate of measuring point #
- y corrdinate of measuring point #

@vsdharun could you double check and confirm ? Thank you

**Comment by sbancal** [comment]
TST_Data_Convention is considered as approved and implemented in the preprocessing pipeline.
I close this issue now.
