### ISSUE TITLE
FIX in TST_Data_Template.xls convention

### ISSUE THREAD

**Issue by sbancal** [EPFL-ENAC/CCFatiguePlatform#56]
Hi,
As I implement the specs in https://github.com/EPFL-ENAC/CCFatiguePlatform/blob/feat/data-validation/Data/TST_Data_Template.xls I realize you set Publication Year to be a string. Shouldn't that be an Int ?

**Comment by vsdharun** [comment]
Yes, I agree that the year should be an integer. We have a few other corrections regarding "time (string)" in the data convention. Congzhe discussed this with me yesterday and he might have communicated with you.

**Comment by sbancal** [comment]
Ok, thank you for your answer.
I change `"Publication>Year"` to `Integer`.

Il let you contact me in an other Issue for an other correction.
