### ISSUE TITLE
Make init-db may be misleading

### ISSUE THREAD

**Issue by pierreleripoll** [EPFL-ENAC/CCFatiguePlatform#63]
Hi ! I ran into a "kind-of" bug when trying to populate the db, if we run `make init-db` and then `make init-db --with-fake-data` the only real experiment won't geet populated with fake tests. 
Maybe we could add a test : if experiment already exists then only populate with fake tests. Because right now I think it's not working because trying to add an already existent experiment will stop the SQL query.
Or, maybe simpler, we could add explicit warning in the documentation to prevent people (like me :stuck_out_tongue:) from running the two commands one after the other.

**Comment by sbancal** [comment]
Will be fixed with #86
