### ISSUE TITLE
Variables consistency validation

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/CCFatiguePlatform#72]
@nicdub - Now with Tassos' answer, can you update the [variables dictionary](https://github.com/EPFL-ENAC/CCFatiguePlatform/tree/develop/Data/variables_dictionary.md) with the comments below, as well as verify that all Data conventions are full and consistent with variable dictionary ?

**Comment by charlottegiseleweil** [comment]
stress_level should be stress_cluster_number 
Add "for Whitney method" in description

**Comment by charlottegiseleweil** [comment]
In variable dicitonary : remove stress_parameter (which in unclear)

In AGG: replace stress parameter by max_stress (sigma_max)

In FAF : replace stress parameter by max_stress (sigma_max)

put stress_max instead of max_stress for consistency

**Comment by nicdub** [comment]
stress_level should be stress_cluster_number, Add "for Whitney method" in description => LinLog, LogLog and Sendeckyj also use stress_level
